config/routes.rb
Rails.application.routes.draw do

  root 'main#home'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :documents do
    get 'public/:uuid', action: :public_show, on: :collection, as: 'public_document'
    patch 'toggle_public_share', action: :toggle_public_share, on: :collection, as: :toggle_public_share
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/document.rb
class Document < ApplicationRecord

  belongs_to :user
  has_one_attached :file
  after_destroy :purge_file
  before_validation :generate_uuid, on: :create

  validates :uuid, presence: true, uniqueness: true
  validates :name, presence: true
  validates :file, presence: true
  validates :upload_date, presence: true
  validates :public_share, inclusion: { in: [true, false] }

  def generate_uuid
    self.uuid ||= SecureRandom.uuid
  end

  validate :file_attached?

  def file_attached?
    errors.add(:file, 'must be attached') unless file.attached?
  end

  private

  def purge_file
    file.purge if file.attached?
  end

end

app/models/user.rb
class User < ApplicationRecord
    has_many :documents

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: true, length: { minimum: 6, maximum: 30 }
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, multiline: true
  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/ }
  validates :password, presence: true, length: { minimum: 8 }, on: :create
  validates :password, length: { minimum: 8 }, allow_blank: false, on: :update

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
    before_action :authenticate_user!, except: [:public_show]

  def index
    @documents = current_user.documents
    @documents_count = @documents.count
  end

  def new
    @document = current_user.documents.new
  end

  def create
    @document = current_user.documents.new(document_params)

    begin
      if @document.save
        redirect_to documents_path, notice: 'File uploaded successfully.'
      else
        flash.now[:alert] = 'Error: Unable to save document.'
        render :new
      end
    rescue => e
      # Log the exception
      flash[:alert] = "Error: #{e.message}"
      redirect_to new_document_path
    end
  end

  def download
    @document = Document.find(params[:id])
    redirect_to rails_blob_path(@document.file, disposition: 'attachment')
  end

  def destroy
    @document = current_user.documents.find(params[:id])
    begin
      ActiveRecord::Base.transaction do
        # Disable automatic purging during the transaction
        @document.file.blob.unfreeze
        # Explicitly purge the attachment if it exists
        @document.file.purge if @document.file.attached?
        # Destroy the document record
        @document.destroy!
      end

      flash[:notice] = 'Document and associated file were successfully destroyed.'
      redirect_to documents_path
    rescue StandardError => e
      flash[:alert] = "Error destroying document: #{e.message}"
      redirect_back(fallback_location: documents_path)
    ensure
      # Re-enable automatic purging after the transaction
      @document.file.blob.freeze
    end
  end

  # Toggle the public_share attribute
  def toggle_public_share
    @document = current_user.documents.find(params[:id])

    if @document && @document.update_attribute(:public_share, !@document.public_share)
        redirect_to documents_path, notice: 'Public sharing status updated.'
    else
        flash[:alert] = 'Error: Unable to update public sharing status.'
        redirect_to documents_path, alert: 'Document not found.'
    end
  end

def public_show
    @document = Document.find_by(uuid: params[:uuid])

    if @document
      render :public_share
    else
      flash[:alert] = 'Document not found.'
      render plain: 'Document not found', status: :not_found
      # redirect_to root_path
    end
end

  private

  def document_params
    params.require(:document).permit(:name, :file, :upload_date, :public_share)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  before_action :configure_permitted_parameters, if: :devise_controller?

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    build_resource(sign_up_params)

    if resource.save
      set_flash_message :notice, :signed_up
      sign_up(resource_name, resource)
      # redirect_to after_update_path_for(resource)
      respond_with resource, location: after_sign_up_path_for(resource)
    else
      clean_up_passwords resource
      set_minimum_password_length
      render :new, status: 422
    end
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)

    if resource.update(account_update_params)
      set_flash_message :notice, :updated
      bypass_sign_in resource, scope: resource_name
      redirect_to after_update_path_for(resource)
      # render json: { message: 'User updated successfully' }, status: :ok
    else
      clean_up_passwords resource
      set_minimum_password_length
      render :edit, status: 422
      # render 'edit'
      # render json: { errors: resource.errors.full_messages }, status: :unprocessable_entity
    end
  end

  # DELETE /resource
#   def destroy
#     super
#   end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
#   def cancel
#     super
#   end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name, :email, :password])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    # super(resource)
    root_path
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :email, :password])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name, :email, :password])
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include ActionView::Helpers::NumberHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/common/_form_error_messages.erb
<% if @document.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>
    <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/documents/index.html.erb
<h1>File Dashboard - <%= @documents_count %> files</h1>

<%= link_to 'Upload New File', new_document_path, class: 'btn btn-primary mb-3' %>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">File</th>
      <th scope="col">Upload Date</th>
      <th scope="col">File Size</th>
      <th scope="col">Sharing</th>
      <th scope="col">Public Link</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @documents.each_with_index do |document, index| %>
      <tr>
        <th scope="row"><%= index + 1 %></th>
        <td><%= document.file.filename.to_s %></td>
        <%
        if document.upload_date.present?
            formatted_date = document.upload_date.strftime('%Y-%m-%d')
        else
            formatted_date = 'N/A'
        end
        %>
        <td><%= formatted_date %></td>
        <td><%= number_to_human_size(document.file.blob.byte_size) %></td>
        <td>
            <%= button_to(document.public_share ? 'Disable' : 'Enable', toggle_public_share_documents_path(document), method: :patch, class: 'btn btn-secondary btn-sm') %>
        </td>
        <td><%= link_to 'Public Link', public_document_documents_path(uuid: document.uuid) %></td>
        <td>
          <%= link_to 'Download', rails_blob_path(document.file, disposition: "attachment"), class: 'btn btn-secondary btn-sm' %>
          <%= link_to 'Delete', document_path(document), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/documents/new.html.erb
<h1>Upload New File</h1>

<%= form_with(model: @document, url: documents_path, multipart: true) do |form| %>
<%= render "common/form_error_messages" %>
  <div class="field">
    <%= form.label :name %><br/>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :upload_date %><br/>
    <%= form.date_field :upload_date %>
  </div>
  <div class="field">
    <%= form.label :file %><br/>
    <%= form.file_field :file %>
  </div>
  <div class="field">
    <%= form.check_box :public_share %>
    <%= form.label :public_share, 'Public Share' %>
  </div><br/>
  <div class="actions">
    <%= form.submit 'Upload', class: 'btn btn-primary' %>
  </div>
<% end %>
<br/>
<%= link_to 'Back', documents_path, class: 'btn btn-primary' %>

app/views/documents/public_share.html.erb
<h3>Shared File from <%= @document.user.name %> (<%= @document.user.username %>) </h3>

<div class="table-responsive">
  <table class="table table-bordered">
    <tbody>
      <tr>
        <th>File Name</th>
        <td><%= @document.name %></td>
      </tr>
      <tr>
        <th>File Owner</th>
        <td><%= @document.user.name %></td>
      </tr>
      <tr>
        <th>File Download</th>
        <td><%= link_to @document.file.filename.to_s, rails_blob_path(@document.file, disposition: "attachment") %></td>
      </tr>
    </tbody>
  </table>
</div>

<%= link_to 'Back to File Dashboard', documents_path, class: 'btn btn-secondary' %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">File Sharing 101</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if current_user %>
        <li class="nav-item"> <%= link_to "File Dashboard", documents_path, class: "nav-link" %></li>
        <% end %>
      </ul>
      
      <ul class="navbar-nav">
        <% if current_user %>
          <%
=begin%>
 <li class="nav-item"> <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %></li> 
<%
=end%>
          <li class="nav-item"> <%= link_to edit_user_registration_path, class: "nav-link" do %> <i class="bi bi-person"></i> <%= current_user.name %> <% end %></li>
          <li class="nav-item"> <%= button_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-small btn-primary mx-2" %></li>
        <% else %>
          <li class="nav-item"> <%= link_to "Sign Up", new_user_registration_path, class: "nav-link"  %></li>
          <li class="nav-item"> <%= link_to "Log In", new_user_session_path, class: "nav-link"  %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>File Sharing 101</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <!-- Include Bootstrap CSS and Bootstrap Icons -->
    <%
=begin%>
 <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap-icons@1.18.0/font/bootstrap-icons.css' %> 
<%
=end%>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <% if flash[:notice] %>
      <div class="alert alert-success alert-dismissible fade show mb-0" role="alert">
        <%= flash[:notice] %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-warning alert-dismissible fade show mb-0" role="alert">
        <%= flash[:alert] %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>

    <div class="container-fluid">

        <%
=begin%>
 <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %> 
<%
=end%>
    <%
=begin%>
 <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> 
<%
=end%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/home.html.erb
<h1>Main#home</h1>
<p>Find me in app/views/main/home.html.erb</p>
<% if current_user %>
  Hello <%= current_user.email %>
<% end %>